POST http://localhost:3001/api/notes 
Content-type: application/json

{
    "content": "Nota para borrar",
    "important": true
}

###             //Las almoadillas son para generar dstintas APIS con fallas para probar errores

POST http://localhost:3001/api/notes 
Content-type: application/json

{
  
}